#!/bin/bash

# Kairos Transcultural Deployment Script for Dokploy
# This script sets up Nginx configuration and SSL for the application

set -e

DOMAIN="kairostranscultural.ifrim.tech"
NGINX_CONF="/etc/nginx/sites-available/$DOMAIN"
ENABLED_CONF="/etc/nginx/sites-enabled/$DOMAIN"

echo "🚀 Deploying Kairos Transcultural to Dokploy..."
echo "Domain: $DOMAIN"

# Step 1: Create Nginx configuration
echo "📝 Creating Nginx configuration..."

sudo tee "$NGINX_CONF" > /dev/null <<EOF
# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name $DOMAIN;
    return 301 https://\$host\$request_uri;
}

# HTTPS server
server {
    listen 443 ssl http2;
    server_name $DOMAIN;

    # SSL certificate (will be generated by Certbot)
    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    include /etc/nginx/snippets/ssl-params.conf;

    # Logging
    access_log /var/log/nginx/${DOMAIN}-access.log;
    error_log /var/log/nginx/${DOMAIN}-error.log;

    # Proxy to Traefik (Dokploy's routing layer)
    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        
        # Headers
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        
        # WebSocket support (if needed for Next.js)
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
EOF

# Step 2: Enable the site
echo "🔗 Enabling Nginx site..."
sudo ln -sf "$NGINX_CONF" "$ENABLED_CONF"

# Step 3: Test Nginx configuration
echo "✅ Testing Nginx configuration..."
if sudo nginx -t; then
    echo "✓ Nginx configuration is valid"
else
    echo "✗ Nginx configuration test failed!"
    exit 1
fi

# Step 4: Generate SSL certificate
echo "🔒 Generating SSL certificate with Certbot..."
if sudo certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos --redirect; then
    echo "✓ SSL certificate generated successfully"
else
    echo "⚠️  Certbot failed. You may need to generate the certificate manually."
    echo "   Run: sudo certbot --nginx -d $DOMAIN"
fi

# Step 5: Reload Nginx
echo "🔄 Reloading Nginx..."
sudo systemctl reload nginx
echo "✓ Nginx reloaded"

echo ""
echo "✅ Nginx setup complete!"
echo ""
echo "📋 Next Steps:"
echo "   1. Go to https://dokploy.ifrim.tech"
echo "   2. Create a new application"
echo "   3. Connect your GitHub repository"
echo "   4. Configure:"
echo "      - Build Type: Dockerfile"
echo "      - Container Port: 3000"
echo "      - Domain: $DOMAIN"
echo "   5. Deploy! 🚀"
echo ""
echo "🔗 Your app will be available at: https://$DOMAIN"
